# Generated by Django 5.1.4 on 2024-12-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("phone_number", models.CharField(max_length=12)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("question", models.CharField(max_length=255)),
                ("comment", models.TextField()),
            ],
        ),
    ]
